### ISSUE TITLE
Doesn't work with Arduino Due - compile error

### ISSUE THREAD

**Issue by myk3y** [platisd/HMC5883L#1]
While compiling:

/var/folders/k5/r37hvq3j32s2lxq6qc3c7k900000gn/T//ccTBql9i.s:1764: Error: bad instruction `jmp 0'

Full compile output at http://pastebin.com/zzTgmJhP

**Comment by platisd** [comment]
Try this library (btw it's just for the magnetometer, not everything else):
https://github.com/platisd/HMC5883L

**Comment by platisd** [comment]
Hi, sorry for the previous comment. I thought I was commenting somewhere else and mistook you for a guy called Mike that i know. :P
So, i compiled the [Simple.ino](https://github.com/platisd/HMC5883L/blob/master/examples/Simple/Simple.ino) sketch that uses this library, selecting it to be compiled for an Arduino Due board, without a problem. I see that in your sketch you are using other libraries such as the Servo or the SD. I think there might be a problem there. Do you mind sharing the code that generated this error?

Thanks

**Comment by myk3y** [comment]
Sorry Dimitris, it was a stray piece of code, as you suspected. Thanks for your help

**Comment by platisd** [comment]
No problem, take care! :)
